[project]
name = "functai-aplicacoes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "attachments>=0.22.0",
    "dspy>=3.0.3",
    "functai>=0.11.0",
    "ovllm>=0.3.0",
]
